# example netlify.toml
[build]
  command = "bun run build"
  functions = "netlify/functions"
  publish = ".next"

[[redirects]]
  from = "http://www.stonfo.com/download/*"
  to = "http://download.stonfo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://stonfo.com/download/*"
  to = "http://download.stonfo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.stonfo.com/download/*"
  to = "http://download.stonfo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://stonfo.com/download/*"
  to = "http://download.stonfo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://stonfo.it/*"
  to = "https://stonfo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.stonfo.it/*"
  to = "https://stonfo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://stonfo.it/*"
  to = "https://stonfo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.stonfo.it/*"
  to = "https://stonfo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://stonfo.netlify.com/download/*"
  to = "http://download.stonfo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://stonfo.netlify.com/*"
  to = "https://stonfo.com/:splat"
  status = 301
  force = true
